# Generated by Django 5.0.6 on 2024-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', 'create_init_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
