# Generated by Django 5.0.6 on 2024-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0001_listing_title_selleruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a detailed description of your listing'),
        ),
    ]
