# Generated by Django 5.0.6 on 2024-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0002_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
