# Generated by Django 5.0.6 on 2024-07-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0003_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='task',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='title',
        ),
    ]
