# Generated by Django 5.0.6 on 2024-07-08 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0004_remove_seller_date_added_remove_seller_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
