# Generated by Django 5.0.6 on 2024-07-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0005_seller_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
