# Generated by Django 5.0.6 on 2024-07-11 14:58
from django.db import migrations
from django.conf import settings
import os
from autohaven_app.models import Listing, ListingImage

def assign_initial_images(apps, schema_editor):
    Listing = apps.get_model('autohaven_app', 'Listing')
    ListingImage = apps.get_model('autohaven_app', 'ListingImage')

    # Define paths to the folders containing initial images
    initial_images_paths = {
        1: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_tesla'),
        2: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_jeep'),
    }

    # Iterate through each listing ID and corresponding folder
    for listing_id, images_path in initial_images_paths.items():
        try:
            listing = Listing.objects.get(id=listing_id)
        except Listing.DoesNotExist:
            print(f"Listing with ID {listing_id} does not exist.")
            continue

        # Iterate through the files in the directory
        for filename in os.listdir(images_path):
            if filename.endswith('.jpg') or filename.endswith('.png'):
                image_path = os.path.join(os.path.basename(images_path), filename)
                ListingImage.objects.create(
                    listing=listing,
                    imagepath=image_path,
                )

class Migration(migrations.Migration):
    dependencies = [
        ("autohaven_app", "0007_initial_offer"),
    ]

    operations = [migrations.RunPython(assign_initial_images),]
