# Generated by Django 5.0.6 on 2024-07-12 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autohaven_app", "0006_alter_listing_mileage"),
        ("autohaven_app", "0008_intial_images"),
    ]

    operations = []
