# Generated by Django 5.0.6 on 2024-06-27 10:25

from django.db import migrations
from autohaven_app.models import Listing
from django.contrib.auth import get_user_model

def create_initial_listings(apps, schema_editor):

    User = apps.get_model('auth', 'User')

    seller_user = User.objects.get(username='seller')
    regular_user = User.objects.get(username='regularuser')

    Listing.objects.create(
        title = 'Tesla On the Market',
        type='new',
        model='Model Y',
        year=2023,
        brand='Tesla',
        mileage=0,
        engine_type='Electric',
        body_type='Hatchback',
        price=80000,
        sold=False,
        description = 'The Tesla Model Y is an all-electric compact crossover SUV that combines the performance and innovation Tesla is known for with the versatility of an SUV. Launched in 2020, it is designed to offer a spacious and high-tech driving experience while maintaining the impressive acceleration and efficiency that Tesla vehicles are celebrated for.',
        user_id= seller_user.id
    )


    regular_user = User.objects.get(username='regularuser')

    Listing.objects.create(
        title='Wrangler In Great Condition',
        type='used',
        model='Wrangler',
        year=2020,
        brand='Jeep',
        mileage=1000,
        engine_type='Pentastar V6',
        body_type='SUV',
        price=80000,
        sold=False,
        description='Get ready to conquer the open road or rugged terrain with this 2017 Jeep Wrangler Unlimited Sahara. This versatile SUV combines classic Jeep ruggedness with modern comforts, making it an ideal choice for adventure seekers and urban drivers alike. With its iconic design and off-road capabilities, this used Wrangler is ready for your next journey.',
        user_id= regular_user.id
    )
 


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0008_create_more_users'),
    ]

    operations = [
        migrations.RunPython(create_initial_listings),
    ]
