# Generated by Django 5.0.6 on 2024-07-11 14:11

from django.db import migrations
from django.conf import settings
from autohaven_app.models import Offer, Listing
from datetime import datetime
from django.contrib.auth import get_user_model

def create_init_offers(apps,schema_editor):

    # Get models
    User = get_user_model()

    user1 = User.objects.get(username='bediuser')
    user2 = User.objects.get(username='berfinuser')


    # Get listing with ID 2
    try:
        listing = Listing.objects.get(id=2)
    except Listing.DoesNotExist:
        print("Listing with ID 2 does not exist.")
        return

    # Create initial offers for each user
    initial_offers = [
        {'user': user1, 'listing': listing, 'offeredPrice': 35000.00, 'status': 'Pending', 'offeredDate': datetime.now()},
        {'user': user2, 'listing': listing, 'offeredPrice': 37000.00, 'status': 'Pending', 'offeredDate': datetime.now()},
    ]

    for offer_data in initial_offers:
        Offer.objects.create(
            user=offer_data['user'],
            listing=offer_data['listing'],
            offeredPrice=offer_data['offeredPrice'],
            offeredDate=offer_data['offeredDate'],
            status=offer_data['status'],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("autohaven_app", "0010_create_intial_images"),
    ]

    operations = [migrations.RunPython(create_init_offers),]
