# Generated by Django 5.0.6 on 2024-07-22 14:32

from django.db import migrations
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    def create_initial_users(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        SellerUser = apps.get_model('autohaven_app', 'SellerUser')
        # Create a seller user
        seller_user, created = User.objects.get_or_create(
            username='seller',
            defaults={
                'first_name': 'Seller',
                'last_name': 'User',
                'email': 'seller@icloud.com',
                'is_staff': False,
                'is_superuser': False
            }
        )

        new_seller_user = SellerUser(company_name="sellerCompany", user = seller_user)
        new_seller_user.save()

    dependencies = [
        ('autohaven_app', '0012_alter_listing_mileage_alter_offer_status'),
    ]

    operations = [migrations.RunPython(create_initial_users),
    ]
