# Generated by Django 5.0.6 on 2024-06-27 10:25

from django.db import migrations
from autohaven_app.models import Listing
from django.contrib.auth import get_user_model

def create_initial_listings(apps, schema_editor):

    User = get_user_model()

    seller_user = User.objects.get(username='seller')

    Listing.objects.create(
        type='new',
        model='Model Y',
        year=2023,
        brand='Tesla',
        mileage=0,
        engine_type='Electric',
        body_type='Hatchback',
        price=80000,
        sold=False,
        user_id= seller_user.id
    )


    regular_user = User.objects.get(username='regularuser')

    Listing.objects.create(
        type='used',
        model='Wrangler',
        year=2020,
        brand='Jeep',
        mileage=1000,
        engine_type='Pentastar V6',
        body_type='SUV',
        price=80000,
        sold=False,
        user_id= regular_user.id
    )
 


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0002_alter_listing_body_type'),
    ]

    operations = [
        migrations.RunPython(create_initial_listings),
    ]
